name: Pulumi AWS Tests

on:
  - pull_request
  - push

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - uses: syphar/restore-virtualenv@v1
      id: pulumi-aws-tests-cache-virtualenv
      with:
        requirement_files: pulumi/aws/requirements.txt

    - uses: syphar/restore-pip-download-cache@v1
      if: steps.pulumi-aws-tests-cache-virtualenv.outputs.cache-hit != 'true'

    # The venv installation script will only be invoked when requirements.txt is changed
    - run: ./setup_venv.sh
      working-directory: pulumi/aws
      if: steps.pulumi-aws-tests-cache-virtualenv.outputs.cache-hit != 'true'

    - name: Test
      working-directory: pulumi/aws
      run: python3 test.py
